### ISSUE TITLE
How to perform side effects?

### ISSUE THREAD

**Issue by Luckey-Elijah** [s0nerik/context_plus#9]
I was looking into this package an curious how to perform side effect such as navigation with `context_plus`. I couldn't find much information on this on pub.dev or the docs

**Comment by s0nerik** [comment]
Currently, `context_plus` doesn't provide a way to add a listener inside the `build` method that would just fire the callback without causing the `BuildContext` to rebuild.

The biggest reason why there's no such API yet is because I want the `context_plus` to not only be convenient, but also correct. Just adding a `.listen(context, (value) => <callback>)` will lead to potentially incorrect behavior if it's used conditionally since it's impossible to know which callback belongs to which code branch:
```dart
if (something) {
  observable.listen(context, (value) => print('listener1'));
} else {
  observable.listen(context, (value) => print('listener2'));
}
```

I haven't come up with an alternative approach that maintains both correctness and conciseness yet.

**Comment by Luckey-Elijah** [comment]
Okay, thank you very much for clarifying!

**Comment by s0nerik** [comment]
Here's what I'm doing currently to achieve what you were looking for:

```dart
final _listener = Ref<VoidCallback>();
...
_listener.bind(
  context,
  () {
    void listener() {
      print('Hello, callback!');
    }

    listenable.addListener(listener);
    return listener;
  },
  dispose: listenable.removeListener,
  key: listenable,
);
```

Looks quite massive, but does the job.

I'm considering options to make this more convenient. It looks possible to condense this into something like
```dart
final _listener = ListenerRef<AnyObservable>(); // or Ref<Listener<AnyObservable>>()
...
_listener.bind(
  context,
  observable,
  () {
    print('Hello, callback!');
  },
);
```

I'm still yet to decide which syntax to choose for this, maybe I'll start a poll somewhere soon. :D Stay tuned!

**Comment by s0nerik** [comment]
After playing around with various options for implementing side effects, I suddenly realized that it's already there in an easy-to-use form. All you need is a `.watchOnly()` call that always returns null.

So, to run a side effect on each notification from the `observable` without causing the widget to rebuild you can do the following:
```dart
observable.watchOnly(context, () {
  print('Hello, callback!');
  return null;
});
```

That's it! As simple as that. Moreover, thanks to the behavioral rules of `.watch()` and `.watchOnly()` calls, the callback is replaceable via hot reload and should properly unregister as soon as the `.watchOnly()` call disappears from the `build` method automatically.

I'll add that to the examples soon.

**Comment by Luckey-Elijah** [comment]
Wow! Surprisingly elegant. Thank you for spending the time investigating this

**Comment by s0nerik** [comment]
@Luckey-Elijah sorry for the misguidance, please see an update on the comment above.

**Comment by s0nerik** [comment]
[context_plus 4.0](https://pub.dev/packages/context_plus/changelog#400) and [context_watch 5.0](https://pub.dev/packages/context_watch/changelog#500) now provide `.watchEffect()` for all supported observable types.
